### ISSUE TITLE
Applications in "Developer Preview" cannot be pinned

### ISSUE THREAD

**Issue by probonopd** [helloSystem/Dock#19]
**Describe the bug**
Applications in "Developer Preview" cannot be pinned

**To Reproduce**
1. Open Disk Utility
2. Try to pin it to the Dock
3. Close Disk Utility
4. Try to open Disk Utility from the Dock

**Expected behavior**
Application opens

**Screenshots**
https://youtu.be/o3z9QnMTLm8?t=522 (thanks Tyler's Tech)

**Version (please complete the following information):**
 - Live ISO or installed system to disk: Installed
 - FreeBSD version (System --> 12.1
 - helloSystem build (`cat /.url`): 0.5.0
 - Running in a virtual machine: no

**Comment by PreyK** [comment]
Saw this too.
Looks to me like the dock doesn't like whitespaces in the launchpath.
Possibly https://github.com/helloSystem/Dock/blob/95fe223b976bc6d34940f9819039200cfa0fa70d/src/applicationmodel.cpp#L125
Launch args being split on whitespaces so the pragram it tries to launch is actually just "Developer" and "Preview/XX" becomes the first arg
Just courious: does this  even need to have launch args? it's just a dock that just supposed to launch stuff on click.

**Comment by PreyK** [comment]
also https://github.com/helloSystem/Dock/issues/11

**Comment by probonopd** [comment]
Luckily, it seems to get pinned correctly in the Dock's `dock_pinned.conf` file:

```
[disk-first-aid.py]
DesktopPath=
Exec=/Applications/Developer Preview/Disk First Aid.app/Disk First Aid
IconName=file:///Applications/Developer Preview/Disk First Aid.app/Resources/Disk First Aid.png
Index=6
visibleName=Disk First Aid
```

**Comment by probonopd** [comment]
Thanks @PreyK that was spot on
