### ISSUE TITLE
The dock does not hide intelligently when the application window is maximized.

### ISSUE THREAD

**Issue by Yakumo-Yukari** [helloSystem/Dock#21]

**Comment by alphamodh0** [comment]
It would be excellent to have a panel that automatically hides when the windows touch it, or when the application is in full screen. This is a bug that I am talking. ![screenshoo](https://user-images.githubusercontent.com/90866187/142780646-e3ef5bb0-7d4b-4f82-8b7e-eb9893659e11.png)
.

**Comment by alphamodh0** [comment]
> It would be excellent to have a panel that automatically hides when the windows touch it, or when the application is in full screen. This is a bug that I am talking. ![screenshoo](https://user-images.githubusercontent.com/90866187/142780646-e3ef5bb0-7d4b-4f82-8b7e-eb9893659e11.png) .

I cannot be happy with this bug :(

**Comment by kettle-7** [comment]
I like to have the dock dodge the focused window. And for maximised the menubar autohides.

**Comment by alphamodh0** [comment]
The hidden global menu should be an option. It would be great to be able to customize some options in the dock.
