### ISSUE TITLE
Dock do'nt show icons.

### ISSUE THREAD

**Issue by alphamodh0** [helloSystem/Dock#27]
The dock does not display most of the application icons. For example: Installing Chromium shows the icon, but then opening it shows the following:
![dock error](https://user-images.githubusercontent.com/90866187/145691923-b1a6865d-7bf8-48e1-b089-dd36d0124357.png)

**Comment by probonopd** [comment]
Duplicate of https://github.com/helloSystem/Dock/issues/26
