### ISSUE TITLE
Allow Dock to be moved and hidden

### ISSUE THREAD

**Issue by grahamperrin** [helloSystem/Dock#4]
The dock should:

* be movable from the bottom (to the left, right or near-top of the screen)
* automatically move to the user-preferred position following a change of resolution 
* automatically hide itself, if required by the user. 

From <https://github.com/helloSystem/ISO/issues/18#issuecomment-752434065>: 

![image](https://user-images.githubusercontent.com/192271/103349451-bf4c5c80-4a94-11eb-8ab4-f3757cbd4d81.png)

<https://www.youtube.com/watch?v=PlPTVbhrKYM&lc=UgzrBzuJGhRHkAUSiW94AaABAg>: 

>  I hope we still get the configuration choice, … auto hiding the dock, …

**Comment by probonopd** [comment]
Did the Dock move to the bottom after a short moment? It should.

As for the rest, someone would need to implement these features because I am not a Qml expert by any stretch of the imagination.

**Comment by grahamperrin** [comment]
Thank you, 

> Did the Dock move to the bottom after a short moment? …

No.

**Comment by probonopd** [comment]
That's a bug then, I opened a separate issue for it.

As for the feature requests, maybe we should check with the upstream https://github.com/cyberos/cyber-dock.

**Comment by grahamperrin** [comment]
https://hellosystem.github.io/docs/developer/ux-guidelines.html#avoiding-configuration-options

> KDE Plasma is recommended as an alternative for users who wish to configure and customize every aspect of the system.
