### ISSUE TITLE
Pinning doesn't set the executable

### ISSUE THREAD

**Issue by darkoverlordofdata** [helloSystem/Dock#8]
I accidentally unpinned Falkon from the dock. After re-pinning, it would not launch. If it’s already open, I can use Dock to switch to it. I investigated the file “/home/darko/.config/cyberos/dock_pinned.conf” and found that the Exec  field was missing: 

``` 
[Falkon] 
DesktopPath= 
Exec= 
IconName=falkon 
Index=5 
visibleName=Falkon 
``` 

I manually reset it using featherpad: 

``` 
[Falkon] 
DesktopPath= 
Exec=falkon 
IconName=falkon 
Index=5 
visibleName=Falkon 
``` 

And now it works. I’ve since recreated this with other apps, and same pattern occurs.

**Comment by probonopd** [comment]
Thanks @darkoverlordofdata.

Whatever we end up doing, we need to make sure that it works for applications in `.app`/`.AppDir` bundles.

**Comment by probonopd** [comment]
I can reproduce this issue. `Exec=` is not populated correctly.

**Comment by probonopd** [comment]
Possibly caused by https://github.com/helloSystem/Dock/issues/18

**Comment by probonopd** [comment]
I believe this is no longer the case in 0.7.0. Please comment here if you think it is not fixed.
